name: dart_datakit
description: Data manipulation library.
version: 1.2.0
homepage: https://github.com/algamesh/dart_datakit
repository: https://github.com/algamesh/dart_datakit
issue_tracker: https://github.com/algamesh/dart_datakit/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:

dev_dependencies:
  test: any
